# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: Tennantco UI Automation
 
variables:
  CI: false
 
trigger:
  - dev
 
jobs:
  - job: test
    timeoutInMinutes: 60
    pool:
      vmImage: "ubuntu-latest"
 
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.16.1"
        displayName: "Install Node.js"
 
      - script: npm ci
        displayName: "Install dependencies"
 
      - script: npx playwright install --with-deps
        displayName: "Install Playwright Browsers"
 
     # - script: xvfb-run tennantco-ui-automation

      - script: npx playwright test
        displayName: "Run Playwright tests"
 
      - publish: $(System.DefaultWorkingDirectory)/playwright-report
        artifact: playwright-report
        condition: always()
      
      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          searchFolder: 'test-results'
          testResultsFormat: 'JUnit'
          testResultsFiles: 'e2e-junit-results.xml'
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: 'End-To-End Tests'
        condition: succeededOrFailed()
        
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: playwright-report
          artifact: playwright-report
          publishLocation: 'pipeline'
        condition: succeededOrFailed()
